/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import javax.swing.JOptionPane;

/**
 *
 * @author Silva
 */
public class batalha2 extends javax.swing.JFrame {

    /**
     * Creates new form batalha2
     */
    public batalha2() {
        initComponents();
         vidaOponente.setMaximum(100); // Define o valor máximo da barra de progresso do oponente
            vidaOponente.setValue(100);
            minhaVida.setMaximum(100); // Define o valor máximo da barra de progresso do oponente
            minhaVida.setValue(100); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ataque2 = new javax.swing.JButton();
        ataque3 = new javax.swing.JButton();
        ataque4 = new javax.swing.JButton();
        ataque1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        minhaVida = new javax.swing.JProgressBar();
        vidaOponente = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000000, 1000000));
        setMinimumSize(new java.awt.Dimension(680, 400));
        getContentPane().setLayout(null);

        jPanel2.setMaximumSize(new java.awt.Dimension(678, 365));
        jPanel2.setLayout(null);

        ataque2.setText("BOLA DE SOMBRA");
        ataque2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataque2ActionPerformed(evt);
            }
        });
        jPanel2.add(ataque2);
        ataque2.setBounds(340, 280, 150, 30);

        ataque3.setText("BOMBA DE LAMA ");
        ataque3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataque3ActionPerformed(evt);
            }
        });
        jPanel2.add(ataque3);
        ataque3.setBounds(190, 320, 150, 30);

        ataque4.setText("HEX");
        ataque4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataque4ActionPerformed(evt);
            }
        });
        jPanel2.add(ataque4);
        ataque4.setBounds(340, 320, 150, 30);

        ataque1.setText("GARRAS DE SOMBRA");
        ataque1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ataque1ActionPerformed(evt);
            }
        });
        jPanel2.add(ataque1);
        ataque1.setBounds(190, 280, 150, 30);

        jButton5.setText("Terminar batalha");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(30, 320, 130, 25);
        jPanel2.add(minhaVida);
        minhaVida.setBounds(80, 140, 146, 14);
        jPanel2.add(vidaOponente);
        vidaOponente.setBounds(500, 130, 146, 14);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("GENGAR");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(80, 120, 70, 19);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SNORLAX");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(500, 110, 80, 19);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagensTelas/tela_batalha2.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 680, 365);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 680, 370);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ataque1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataque1ActionPerformed
      
        
        if (minhaVida.getValue() <= 0 || vidaOponente.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A batalha acabou!", "Fim da Batalha", JOptionPane.INFORMATION_MESSAGE);
            return;  //  Não execute mais ações se a batalha acabou
        }
        
        
        int seuDano = 10;  // Dano que seu ataque causa
    int seuContraAtaque = 20;  // Dano que o oponente causa em você

    int vidaAtualOponente = vidaOponente.getValue();
    int vidaAtualSua = minhaVida.getValue();

    if (vidaAtualOponente - seuDano >= 0) {
        vidaAtualOponente -= seuDano;
    } else {
        vidaAtualOponente = 0;
    }

    vidaOponente.setValue(vidaAtualOponente);

    if (vidaAtualOponente == 0) {
        JOptionPane.showMessageDialog(this, "O oponente foi derrotado!", "Vitória", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a vitória.
        return;
    }

    // Verifique se sua vida chegou a zero
    if (vidaAtualSua - seuContraAtaque >= 0) {
        vidaAtualSua -= seuContraAtaque;
    } else {
        vidaAtualSua = 0;
        JOptionPane.showMessageDialog(this, "Você foi derrotado pelo oponente!", "Derrota", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a derrota.
        return;
    }

    minhaVida.setValue(vidaAtualSua);

    // Exiba informações em um JOptionPane
    String mensagem = "Garras de sombra causou " + seuDano + " de dano ao oponente.\n";
    mensagem += "O oponente contra-atacou e causou " + seuContraAtaque + " de dano em você.";

    JOptionPane.showMessageDialog(this, mensagem, "Resultado do Ataque", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ataque1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       dispose();
       new conversa3().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ataque2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataque2ActionPerformed
          if (minhaVida.getValue() <= 0 || vidaOponente.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A batalha acabou!", "Fim da Batalha", JOptionPane.INFORMATION_MESSAGE);
            return;  //  Não execute mais ações se a batalha acabou
        }
        
        
        int seuDano = 25;  // Dano que seu ataque causa
    int seuContraAtaque = 10;  // Dano que o oponente causa em você

    int vidaAtualOponente = vidaOponente.getValue();
    int vidaAtualSua = minhaVida.getValue();

    if (vidaAtualOponente - seuDano >= 0) {
        vidaAtualOponente -= seuDano;
    } else {
        vidaAtualOponente = 0;
    }

    vidaOponente.setValue(vidaAtualOponente);

    if (vidaAtualOponente == 0) {
        JOptionPane.showMessageDialog(this, "O oponente foi derrotado!", "Vitória", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a vitória.
        return;
    }

    // Verifique se sua vida chegou a zero
    if (vidaAtualSua - seuContraAtaque >= 0) {
        vidaAtualSua -= seuContraAtaque;
    } else {
        vidaAtualSua = 0;
        JOptionPane.showMessageDialog(this, "Você foi derrotado pelo oponente!", "Derrota", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a derrota.
        return;
    }

    minhaVida.setValue(vidaAtualSua);

    // Exiba informações em um JOptionPane
    String mensagem = "Bola de sombra causou " + seuDano + " de dano ao oponente.\n";
    mensagem += "O oponente contra-atacou e causou " + seuContraAtaque + " de dano em você.";

    JOptionPane.showMessageDialog(this, mensagem, "Resultado do Ataque", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ataque2ActionPerformed

    private void ataque3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataque3ActionPerformed
         if (minhaVida.getValue() <= 0 || vidaOponente.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A batalha acabou!", "Fim da Batalha", JOptionPane.INFORMATION_MESSAGE);
            return;  //  Não execute mais ações se a batalha acabou
        }
        
        
        int seuDano = 15;  // Dano que seu ataque causa
    int seuContraAtaque = 20;  // Dano que o oponente causa em você

    int vidaAtualOponente = vidaOponente.getValue();
    int vidaAtualSua = minhaVida.getValue();

    if (vidaAtualOponente - seuDano >= 0) {
        vidaAtualOponente -= seuDano;
    } else {
        vidaAtualOponente = 0;
    }

    vidaOponente.setValue(vidaAtualOponente);

    if (vidaAtualOponente == 0) {
        JOptionPane.showMessageDialog(this, "O oponente foi derrotado!", "Vitória", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a vitória.
        return;
    }

    // Verifique se sua vida chegou a zero
    if (vidaAtualSua - seuContraAtaque >= 0) {
        vidaAtualSua -= seuContraAtaque;
    } else {
        vidaAtualSua = 0;
        JOptionPane.showMessageDialog(this, "Você foi derrotado pelo oponente!", "Derrota", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a derrota.
        return;
    }

    minhaVida.setValue(vidaAtualSua);

    // Exiba informações em um JOptionPane
    String mensagem = "bomba de lama causou " + seuDano + " de dano ao oponente.\n";
    mensagem += "O oponente contra-atacou e causou " + seuContraAtaque + " de dano em você.";

    JOptionPane.showMessageDialog(this, mensagem, "Resultado do Ataque", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ataque3ActionPerformed

    private void ataque4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ataque4ActionPerformed
        if (minhaVida.getValue() <= 0 || vidaOponente.getValue() <= 0) {
            JOptionPane.showMessageDialog(this, "A batalha acabou!", "Fim da Batalha", JOptionPane.INFORMATION_MESSAGE);
            return;  //  Não execute mais ações se a batalha acabou
        }
        
        
        int seuDano = 25;  // Dano que seu ataque causa
    int seuContraAtaque = 10;  // Dano que o oponente causa em você

    int vidaAtualOponente = vidaOponente.getValue();
    int vidaAtualSua = minhaVida.getValue();

    if (vidaAtualOponente - seuDano >= 0) {
        vidaAtualOponente -= seuDano;
    } else {
        vidaAtualOponente = 0;
    }

    vidaOponente.setValue(vidaAtualOponente);

    if (vidaAtualOponente == 0) {
        JOptionPane.showMessageDialog(this, "O oponente foi derrotado!", "Vitória", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a vitória.
        return;
    }

    // Verifique se sua vida chegou a zero
    if (vidaAtualSua - seuContraAtaque >= 0) {
        vidaAtualSua -= seuContraAtaque;
    } else {
        vidaAtualSua = 0;
        JOptionPane.showMessageDialog(this, "Você foi derrotado pelo oponente!", "Derrota", JOptionPane.INFORMATION_MESSAGE);
        // Faça o que for necessário após a derrota.
        return;
    }

    minhaVida.setValue(vidaAtualSua);

    // Exiba informações em um JOptionPane
    String mensagem = "Hex causou " + seuDano + " de dano ao oponente.\n";
    mensagem += "O oponente contra-atacou e causou " + seuContraAtaque + " de dano em você.";

    JOptionPane.showMessageDialog(this, mensagem, "Resultado do Ataque", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_ataque4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(batalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(batalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(batalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(batalha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new batalha2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ataque1;
    private javax.swing.JButton ataque2;
    private javax.swing.JButton ataque3;
    private javax.swing.JButton ataque4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar minhaVida;
    private javax.swing.JProgressBar vidaOponente;
    // End of variables declaration//GEN-END:variables
}
